# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.13.0/www/docs/static/schema.json
version: 2
project_name: vault-migrate

builds:
  - id: vault-migrate
    main: .
    binary: vault-migrate
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    targets:
      - linux_amd64_v1
      - linux_arm64
      - darwin_amd64_v1
      - darwin_arm64
      - windows_amd64_v1
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: binaries
    ids:
      - vault-migrate
    formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ .ArtifactExt }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  disable: true
